[
    "js/vendor/bootstrap-material-design/ripples.js",
    "js/vendor/bootstrap-material-design/material.js",
    "js/modules/util.js",
    "js/modules/file-input.js",
    "js/modules/loading.js",
    "js/modules/responsive-text.js",
    "js/modules/tree-view.js",
    "js/modules/sidebar-toggle.js",
    "js/modules/collapse-nav-sub.js",
    "js/modules/zclip.js",
    "js/modules/random-background-color.js",
    "js/modules/optional.js"
]